"use client"

// import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import { ThemeProvider } from "styled-components";

import { themes } from "@/global/theme";
import Global from "@/global/styles";
import Notification from "@/hooks/notification";

const inter = Montserrat({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt">
      <ThemeProvider theme={themes}>
          <body className={inter.className}>
            <Notification>
              {children}
            </Notification>
          </body>
        <Global />
      </ThemeProvider>
    </html>
  );
}
