"use client"

// import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import { ThemeProvider } from "styled-components";

import { themes } from "@/global/theme";
import Global from "@/global/styles";
import Notification from "@/hooks/notification";

const font = Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
  style: ['italic', 'normal'],
  subsets: ['latin'],
  variable: '--font-montserrat',
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={font.variable}>
      <ThemeProvider theme={themes}>
          <body >
            <Notification>
              {children}
            </Notification>
          </body>
        <Global />
      </ThemeProvider>
    </html>
  );
}
